# Introduction

It turns out that lists are not perfect for numerical computations. Due to the way they are implemented, computations with lists are too slow. This is due to the fact that Python was not designed with computational mathematics as a priority. This should not come as a surprise: modern computer languages have a huge range of applications, and it is not possible to include optimized features for all possible uses of the language.

The module `numpy` ("numerical python") was designed to overcome the limitations of the `list` datatype. `numpy` defines data structures and functions that are suitable for scientific computing. The most important of such structures is `ndarray`, which is used to represent arrays with one or more dimensions.

To use the module `numpy`, it must first be imported, as shown in the following cell:

In [4]:
import numpy as np

# Constructing arrays

The most straightforward method to define an array is to construct it from a regular Python list:

In [5]:
u = np.array([2,5,-1,4,7,0])
u

array([ 2,  5, -1,  4,  7,  0])

There is a very important point in which arrays are different from lists. *All elements of an array must have the same type*. Technically, every array has a `dtype`. The `d` in `dtype` stands for "data", that is, `dtype` indicates what is the data type of elements of the array. To see what is the type of the array `u` we can use the following code:

In [7]:
u.dtype

dtype('int64')

There is another important point here: usually we _don't_ want to work with integers when doing numerical work. To create an array of floats, we have two possible syntaxes:

In [8]:
v = np.array([2.,5.,-1.,4.,7.,0.])
v

array([ 2.,  5., -1.,  4.,  7.,  0.])

In [9]:
w = np.array([2,5,-1,4,7,0], dtype=np.float64)
w

array([ 2.,  5., -1.,  4.,  7.,  0.])

If you are getting unexpected results when working with arrays, the first thing to check is if the arrays in your code have the correct `dtype`.

Arrays use the same syntax as lists to refer to elements and slices:

In [10]:
v[3]

4.0

In [11]:
v[2] = 10
v

array([ 2.,  5., 10.,  4.,  7.,  0.])

(Notice the automatic conversion to `float`.)

In [12]:
v[1:4]

array([ 5., 10.,  4.])

In [13]:
v[0:5:2]

array([ 2., 10.,  7.])

Arrays have a powerful indexing facility that is not available for lists. Let's say we need to extract the elements with indexes 2, 5 and 1, in this order. This is how it can be done:

In [14]:
v[ [2, 5, 1] ]

array([10.,  0.,  5.])

Notice how the indexes are specified in the input cell. We are using the _list_ `[2, 5, 1]` as the index for the array. We can actually even use an array as the index for an array with similar results.

As with lists, we can define array ranges, with the `arange` function:

In [15]:
t = np.arange(2, 10)
t

array([2, 3, 4, 5, 6, 7, 8, 9])

Notice that this is an array of integers. We can specify the `dtype` to make this an array of floats:

In [16]:
t = np.arange(2, 10, dtype=np.float64)
t

array([2., 3., 4., 5., 6., 7., 8., 9.])

This is actually one of the main advantages of an `arange` over a `range`: we can have floats in an `arange`. As with a `range`, we can specify a step with a third argument:

In [17]:
r = np.arange(3, 7, .4)
r

array([3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8, 6.2, 6.6])

Notice that we didn't need to specify the `dtype`. `numpy` is smart enough to realize that this should be an array of floats.

Finaly, there is `linspace`, which is very useful in many situations. `linspace` generates a specified number of equally spaced points between two given values. For example, to get 5 equally spaced points between 2 and 7, use:

In [18]:
p = np.linspace(2, 7, 5)
p

array([2.  , 3.25, 4.5 , 5.75, 7.  ])

Notice that the endpoint 7 _is included_ in the array. This is an exception to the normal rule for sequence-type data structures in Python, but it is a convenient one. `linspace` is designed for case in which we need a regular grid of points in an interval, which is very common in numerical computing.

# Array functions and methods

Many of the list functions and methods have array counterparts. The length of an array is computed by the `len()` function:

In [21]:
print(v)
len(v)

[ 2.  5. 10.  4.  7.  0.]


6

Elements of an array can be sorted in-place with the `sort()` function:

In [22]:
v.sort()
v

array([ 0.,  2.,  4.,  5.,  7., 10.])

On the other hand, some list functions don't work with arrays. Suppose we want to append an element to an array. It looks like we could use something like:

In [23]:
v.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

There is a good reason why the method `append()` is not defined for `numpy` arrays. An array can be multidimensional, and it does not make much sense to append a single element to a multidimensional data structure. For example, it is not clear to what dimension the new element should be appended. 

There is a function `append` in the module `numpy`, but this method does not work as expected. For example, consider the following code:

In [24]:
w = np.append(v,3)
print(v)
print(w)

[ 0.  2.  4.  5.  7. 10.]
[ 0.  2.  4.  5.  7. 10.  3.]


The `numpy` function `append()` does not change the input array in-place. Instead, it returns an array with the appended element.

# Higher dimensional arrays

Arrays can have any number of dimensions. The following defines a two-dimensional array (also known as a matrix, of course):

In [32]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

When accessing the elements of a multidimensional array, remember that all dimensions start at the index 0:

In [33]:
A[0,2]

3

Notice that, in the example above, we used "matrix notation" `A[i,j]` to access an array element. Notice that this is not allowed with lists. If `A` were a "list of lists", to reference elements of `A` one would have to use the notation `A[i][j]`.

To find the dimensions of an array, we use the `shape` field of the array:

In [34]:
A.shape

(3, 4)

Notice that `shape` is not a method, so we don't use the function call notation. `A.shape()` is a syntax error.

The `size` of an array is the total number of elements:

In [35]:
A.size

12

Slices in multidimensional arrays are very powerful. We can select almost any kind of subarray we can imagine. For example, to extract a submatrix of `A` with rows 1 to 3 and columns 0 to 2, we can use the slice:

In [36]:
A[1:3, 0:2]

array([[ 5,  6],
       [ 9, 10]])

Notice that slices follow the Python convention don't include the endpoint of the range. So, the slice `1:3` refers to rows 1 and 2 only.

The following are common idioms for extracting rows and columns of a two dimensional array:

In [37]:
A[1,:]  # Second row

array([5, 6, 7, 8])

In [38]:
A[:,2]  # Third column

array([ 3,  7, 11])

Notice that there is something strange with this last example. It seems that the the column is returned as a row vector. This is a good point to discuss in more detail the structure of `ndarray` objects.

When we construct a one-dimensional array in Python, what we are actually defining is something called a `rank one array`. At first glance, it seems that this data structure represents a row vector or a column vector, but in truth it represents neither. To better understand this, let's construct a one-dimensional array and find its shape:

In [40]:
rank_one_array = np.array([1, 5, 3, -2, 4])
print(rank_one_array)
print(rank_one_array.shape)

[ 1.  5.  3. -2.  4.]
(5,)


Notice that the shape of the array looks a little strange. `(5,)` denotes a Python `tuple` with a single element. A `tuple` is a Python datatype that represents an immutable sequence of data, and will be discussed in detail later in the course.

For now, the important point is that this is neither a column or a row of data. The `numpy` designers decided that it was convenient to have a data structure that defines a one-dimensional sequence that is not tought of as neither a column or a row.

In mathematics, we identify a column $n$-vector with a $n\times 1$ matrix. We can define this in Python using the following code:

In [42]:
column_vector = np.array([1,5,3,-2,4]).reshape(5,1)
column_vector

array([[ 1],
       [ 5],
       [ 3],
       [-2],
       [ 4]])

Analogously, to construct a row vector we can use:

In [43]:
row_vector = np.array([1,5,3,-2,4]).reshape(1,5)
row_vector

array([[ 1,  5,  3, -2,  4]])

Notice that this is different from:

In [44]:
np.array([1,5,3,-2,4])

array([ 1,  5,  3, -2,  4])

Some people say that rank-one arrays should never be used in numerical computations. In our opinion, this is an overkill. In cases where it does not matter if the data is visualized as a column or a row, it is fine to use rank-one arrays. However, in some cases, it *does* matter how the data is oriented. For example, suppose we want to compute the matrix multiplication:
$$
Av
$$
If the matrix is $m\times n$, we expect $v$ to be a column vector, with dimensions $n\times 1$, and the result to be a column vector with dimensions $m\times 1$. The following cell illustrates how this can be done:

In [45]:
A = np.array([[1,3,4,2],[2,1,-3,4],[2,1,1,0]])
print(A)
v = np.array([1,3,-2,1]).reshape(4,1)
print(A)
w = A @ v
print(w)

[[ 1  3  4  2]
 [ 2  1 -3  4]
 [ 2  1  1  0]]
[[ 1  3  4  2]
 [ 2  1 -3  4]
 [ 2  1  1  0]]
[[ 4]
 [15]
 [ 3]]


Notice the use of the operator `@` for matrix multiplication. This is a special operator introduced in Python just for matrix multiplication. See the section below on array operations for a more thorough discussion.

# Special Arrays

`numpy` has several predefined functions designed to create commonly used arrays. For example, to create an array of zeros we can use:

In [46]:
np.zeros((2,3))   # 2 x 3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

An array of ones can be created as follows:

In [47]:
np.ones((4,3))   # 4 x 3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

The identity matrix is constructed with the `eye()` function. When calling this function, we need to specify the dimension of the matrix:

In [49]:
np.eye(4)   # 4 x 4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

By the way, did you get the nerd joke? "Eye" sounds like "I", which is the mathematical symbol for the identity matrix. The `numpy` designers decided that using `eye()` instead of `I()` makes the code more readable.

We can create a diagonal matrix with the following code:

In [51]:
np.diag([2,-3,4,5])

array([[ 2,  0,  0,  0],
       [ 0, -3,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  5]])

In numerical computations, we frequently need to create matrices with random elements. This can be done with the function `np.random.rand()`:

In [55]:
A = np.random.rand(2, 4)  # 2 x 4 matrix with random entries
A

array([[0.35882031, 0.88738094, 0.00472953, 0.04885521],
       [0.15531096, 0.67166085, 0.84795072, 0.16038851]])

The function `rand()`, by default, generates random numbers uniformly distributed in the range $[0,1]$. If, for example, we need random numbers in the range $[0, 0.25]$, we can scale the result as follows:

In [56]:
B = np.random.rand(2, 4) * 0.25
B

array([[0.06972215, 0.20450678, 0.14990585, 0.22618928],
       [0.08008589, 0.08607766, 0.02922528, 0.18808935]])

`numpy` also supports the generation of non-uniform random numbers. For example, to generate a column vector of normally-distributed random values we can use:

In [57]:
C = np.random.randn(4, 1) # 4 x 1 matrix with normally distributed random values
C

array([[-0.1731404 ],
       [ 0.9423696 ],
       [-0.01764866],
       [ 0.87737531]])

The `randn()` function, by default, generates values according to a normal distribution with mean 0 and standard deviation 1. To change the mean and standard deviation we can scale-and-shift the output from `randn()`, as follows:

In [58]:
D = 2 + 1.5 * np.random.randn(4,1) # normally distributed random values with mean 2 and sdev 1.5
D

array([[1.59347046],
       [2.90605106],
       [1.35379454],
       [4.47717497]])

A final note to nitpickers: we know that, technically, computers can't generate random numbers, and the word *pseudorandom* should be used. 

# Array operations

`numpy` defines most arithmetic operations between arrays. Here are a few examples:

In [31]:
u = np.array([2.,-1.,0.,2.])
v = np.array([3.,6.,-4.,1.])

In [32]:
u + v

array([ 5.,  5., -4.,  3.])

In [33]:
u * v

array([ 6., -6., -0.,  2.])

In [34]:
u / v

array([ 0.66666667, -0.16666667, -0.        ,  2.        ])

In [35]:
-u

array([-2.,  1., -0., -2.])

In [36]:
3 * u

array([ 6., -3.,  0.,  6.])

In [37]:
v ** 2

array([ 9., 36., 16.,  1.])

Notice that all operations are element by element. In particular, multiplication is _not_ the vector dot product. For this, use the function `dot`:

In [38]:
np.dot(u,v)

2.0

This is also available as a method, which is useful sometimes:

In [39]:
u.dot(v)

2.0

Using the operator `*` with multidimensional arrays is tricky, it uses a convention called _broadcasting_ that is not completely intuitive. So, if you want to do matrix multiplication, always use the `dot()` method. The matrices must be of compatible size, of course. For example:

In [40]:
A = np.array([[1,-1,-2,0],[2,0,3,-4]], dtype=np.float64)
A

array([[ 1., -1., -2.,  0.],
       [ 2.,  0.,  3., -4.]])

In [41]:
B = np.array([[1,3],[-1,4],[0,5],[-3,2]], dtype=np.float64)

In [42]:
A.dot(B)

array([[  2., -11.],
       [ 14.,  13.]])

There also is a subclass `matrix` of `array` that defines operations and methods that are useful for doing linear algebra. It is less efficient than plain `array`s, but it is handy for quick computations.

# Vectorized functions

A very useful characteristic of arrays are _vectorized functions_. These are functions that operate on every element of an array individually. `numpy` defines vectorized versions of all elementary functions. For example, let's say we need the sines of the angles $0$, $\pi/3$, $2\pi/3$ up to $\pi$. We first generate an array with the points we need: 

In [43]:
xvalues = np.arange(0, np.pi + 0.1, np.pi/3)
xvalues

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

(Question: why did we use `np.pi + 0.1` as the upper bound for the `arange`?)

Now, to compute the sines of these angles, simply use:

In [44]:
yvalues = np.sin(xvalues)
yvalues

array([0.00000000e+00, 8.66025404e-01, 8.66025404e-01, 1.22464680e-16])

(Question: shouldn't $\sin(\pi)$ be zero? Why is it not?)

Some of the vectorized functions defined by `numpy` are:

- Square, square root, absolute value: `square`, `sqrt`, `abs`.
- Trigonometric and inverse trigonometric functions: `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`.
- Exponential and logarithmic functions: `exp`, `log`, `log10`, `log2`.
- Hyperbolic functions: `sinh`, `cosh`, `tanh`, `arcsinh`, `arccos`, `arctanh`.
- Rounding: `round`, `trunc`, `floor`, `ceil`.

Check the documentation for a complete list, as well as specifics for individual functions.

Notice that `log` is the natural logarithm:

In [45]:
np.log(10)

2.302585092994046

`log10` is the logarithm in base 10:

In [46]:
np.log10(10)

1.0

Finally, `log2` is the logarithm in base two. To compute a logarithm in an arbitrary base, you have to use the change of base formula. For example, the logarithm of 531441
in base 3, do:

In [47]:
np.log(531441)/np.log(3)

12.0

If you ever used the `math` module in plain Python, notice that the `log` function behaves differently.

Operations are also vectorized. For example:

In [48]:
u = np.array([2, 5, 1, -3], dtype=np.float64)
v = np.array([4, 1, -2, 0], dtype=np.float64)
u, v

(array([ 2.,  5.,  1., -3.]), array([ 4.,  1., -2.,  0.]))

In [49]:
u + v

array([ 6.,  6., -1., -3.])

In [50]:
u - v

array([-2.,  4.,  3., -3.])

In [51]:
u * v

array([ 8.,  5., -2., -0.])

In [52]:
2 * u

array([ 4., 10.,  2., -6.])

In [53]:
u ** 3

array([  8., 125.,   1., -27.])

In [54]:
3 ** u

array([9.0000000e+00, 2.4300000e+02, 3.0000000e+00, 3.7037037e-02])

In [55]:
u ** v

array([16.,  5.,  1.,  1.])

Notice that all operations are defined _componentwise_, so the arrays must have the same dimension (unless one of the operands is a scalar). 

In particular, notice that `*` is _not_ the dot product of vectors. To compute that, use the `dot` function:

In [56]:
np.dot(u,v)

11.0

Vectorized operations and functions should be used whenever possible, since this is the most efficient way to do computations with arrays. For example, suppose that `x` and `y` contain the coordinates of a list of points:

In [57]:
x = np.linspace(2, 6, 5)
y = np.linspace(-3, 4, 5)
x, y

(array([2., 3., 4., 5., 6.]), array([-3.  , -1.25,  0.5 ,  2.25,  4.  ]))

To compute an array with the distances from the points to the origin, we can use:

In [58]:
distances = (x - y) ** 2
distances

array([25.    , 18.0625, 12.25  ,  7.5625,  4.    ])

# Exercises

# What you learned in this lesson

# Further information