# Introduction

In this lesson, we will learn about Python's *flow control* statements. These include `for` and `while` loops, which execute a block of code until some condition is reached. These are important programming structures that appear in almost any Python program. 

# `for` loops

`for` loops perform a set task in a repeated manner over a range of indices. This repeated action is often referred to as a loop


Below is an example of `for` loop that prints all integers from 0 to 9 and their squares:

In [ ]:
for n in range(10):
    print(f'The square of {n} is {n ** 2}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81


Note that the spacing matters, where a 'tab' spacing designates what is done in the loop. Anything following the colon is the action that is repeated.

When this code is executed, Python assigns the values in `range(10)` successively to the variable `n`, and then executes the indented statement:

    print(f'The square of {n} is {n ** 2}')

The general structure of a `for` loop is:

    for <identifier> in <iterable>:
        <indented block>
        
An *iterable* is a Python object capable of returning its members one at a time. Examples of iterables are lists, tuples and strings, but other types of objects, such as dictionaries and sets, are also iterable. In the example above, the iterable is `range(10)`. Range objects are a special kind of object that supports iteration on a set of equally spaced integer values.

*Technical note*: A range object can be tought as a list, but internally it is represented by a different type of object. The reason for that is efficiency. The elements of a range are only generated as needed, while a list must be kept in memory in its entirety.

Let's play around with the range function, just to be comfortable with what it produces. 

Calling `range(0,10)` will produce a list of 10 integers from 0 to 9. Note that it does not include 10.

In [6]:
for n in range(0,10):
  print(n)

0
1
2
3
4
5
6
7
8
9


If we wanted to cycle through integers from 1 to 10, then we would call `range(1,11)`.

In [7]:
for n in range(1,11):
  print(n)

1
2
3
4
5
6
7
8
9
10


The `<indented block>` in a `for` loop can be any sequence of indented Python commands. In the following example, we compute the sum of all integers from 1 to 100, as well as the sum of their squares:

In [ ]:
sum_values = 0
sum_squares = 0
for n in range(1, 101):
    sum_values += n
    sum_squares += n * n
print(f'Sum: {sum_values}\nSum of squares: {sum_squares}')

Sum: 5050
Sum of squares: 338350


The iterator in a `for` loop does not have to be a range. The next example shows how to compute the product of the elements of a list:

In [ ]:
numbers = [2, 3, -5, 4, -2, 9]
product = 1
for n in numbers:
    product *= n
print(f'The product of the numbers is {product}')

The product of the numbers is 2160


It is also possible to iterate over`numpy` arrays, but we must be a little careful. Consider the following example:

In [13]:
import numpy as np
A = np.random.random((4,4))
for row in A:
    print(row)

[0.24324773 0.83675674 0.81952965 0.67221482]
[0.74814452 0.44339894 0.79562484 0.45387084]
[0.1448084  0.73814563 0.90587627 0.32389809]
[0.2678694  0.92059369 0.01361108 0.60406369]


Notice that this iterates over the *rows* of the two-dimensional array `A`. If we want to iterate over each element separately we can use nested loops:

In [15]:
sum_of_elements = 0
for row in A:
    for value in row:
        sum_of_elements += value
print(f'The sum of the elements of A is {sum_of_elements}')

The sum of the elements of A is 8.93165433236993


### Exercises

1. Compute $2^n$ for the first 100 integers, with $n=0$ being your initial value.

2. Use a `for` loop to compute the first 20 numbers in a  Fibonacci sequence. Fibonacci sequence is defined by the previous numbers
$$x_{n+1}=x_{n}+x_{n-1}$$
where $x_0=0$ and $x_1=1$. 
Fix the following incomplete code to compute the first 20 Fibonacci numbers in a numpy array.
```
F=np.zeros(20)
F[0]=0
F[1]=1
for n in range(FILL, OUT):
  F[?]=
print(F)
```
Note `F[0]` represents $x_0$ and `F[1]` represents $x_1$.

3. Compute the column sum of the matrix A:
```
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, -1, -2, -3],[-4, -5, -6, -7]])
```
Hint: use `col` to iterate.

# Using `for` and `if` loops together

Sometimes 