# Introduction

In this lesson, we will learn about Python's *flow control* statements. These include `for` and `while` loops, which execute a block of code until some condition is reached. These are important programming structures that appear in almost any Python program. 

# `for` loops

Below is an example of `for` loop that prints all integers from 0 to 9 and their squares:

In [2]:
for n in range(10):
    print(f'The square of {n} is {n ** 2}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81


When this code is executed, Python assignes the values in `range(10)` successively to the variable `n`, and then executes the indented statement:

    print(f'The square of {n} is {n ** 2}')

The general structure of a `for` loop is:

    for <identifier> in <iterable>:
        <indented block>
        
An *iterable* is a Python object capable of returning its members one at a time. Examples of iterables are lists, tuples and strings, but other types of objects, such as dictionaries and sets, are also iterable. In the example above, the iterable is `range(10)`. Range objects are a special kind of object that supports iteration on a set of equally spaced integer values.

*Technical note*: A range object can be tought as a list, but internally it is represented by a different type of object. The reason for that is efficiency. The elements of a range are only generated as needed, while a list must be kept in memory in its entirety.

The `<indented block>` in a `for` loop can be any sequence of indented Python commands. In the following example, we compute the sum of all integers from 1 to 100, as well as the sum of their squares:

In [7]:
sum_values = 0
sum_squares = 0
for n in range(1, 101):
    sum_values += n
    sum_squares += n * n
print(f'Sum: {sum_values}\nSum of squares: {sum_squares}')

Sum: 5050
Sum of squares: 338350


The iterator in a `for` loop does not have to be a range. The next example shows how to compute the product of the elements of a list:

In [10]:
numbers = [2, 3, -5, 4, -2, 9]
product = 1
for n in numbers:
    product *= n
print(f'The product of the numbers is {product}')

The product of the numbers is 2160


It is also possible to iterate over`numpy` arrays, but we must be a little careful. Consider the following example:

In [14]:
import numpy as np
A = np.random.random((4,4))
for row in A:
    print(row)

[0.96737623 0.16186401 0.96125718 0.42734536]
[0.05210643 0.90011304 0.79235528 0.1597244 ]
[0.91670954 0.21845037 0.76251124 0.51880728]
[0.5789509  0.9770197  0.4761449  0.39741368]


Notice that this iterates over the *rows* of the two-dimensional array `A`. If we want to iterate over each element separately we can use nested loops:

In [17]:
sum_of_elements = 0
for row in A:
    for value in row:
        sum_of_elements += value
print(f'The sum of the elements of A is {sum_of_elements}')

The sum of the elements of A is 9.268149530610502


9