# Introduction

In this lesson, we will learn about Python's *flow control* statements. These include `for` and `while` loops, which execute a block of code until some condition is reached. These are important programming structures that appear in almost any Python program. 

# `for` loops

`for` loops perform a set task in a repeated manner over a range of indices. This repeated action is often referred to as a loop


Below is an example of `for` loop that prints all integers from 0 to 9 and their squares:

In [ ]:
for n in range(10):
    print(f'The square of {n} is {n ** 2}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81


Note that the spacing matters, where a 'tab' spacing designates what is done in the loop. Anything following the colon is the action that is repeated.

When this code is executed, Python assigns the values in `range(10)` successively to the variable `n`, and then executes the indented statement:

    print(f'The square of {n} is {n ** 2}')

The general structure of a `for` loop is:

    for <identifier> in <iterable>:
        <indented block>
        
An *iterable* is a Python object capable of returning its members one at a time. Examples of iterables are lists, tuples and strings, but other types of objects, such as dictionaries and sets, are also iterable. In the example above, the iterable is `range(10)`. Range objects are a special kind of object that supports iteration on a set of equally spaced integer values.

*Technical note*: A range object can be tought as a list, but internally it is represented by a different type of object. The reason for that is efficiency. The elements of a range are only generated as needed, while a list must be kept in memory in its entirety.

Let's play around with the range function, just to be comfortable with what it produces. 

Calling `range(0,10)` will produce a list of 10 integers from 0 to 9. Note that it does not include 10.

In [6]:
for n in range(0,10):
  print(n)

0
1
2
3
4
5
6
7
8
9


If we wanted to cycle through integers from 1 to 10, then we would call `range(1,11)`.

In [7]:
for n in range(1,11):
  print(n)

1
2
3
4
5
6
7
8
9
10


The `<indented block>` in a `for` loop can be any sequence of indented Python commands. In the following example, we compute the sum of all integers from 1 to 100, as well as the sum of their squares:

In [ ]:
sum_values = 0
sum_squares = 0
for n in range(1, 101):
    sum_values += n
    sum_squares += n * n
print(f'Sum: {sum_values}\nSum of squares: {sum_squares}')

Sum: 5050
Sum of squares: 338350


The iterator in a `for` loop does not have to be a range. The next example shows how to compute the product of the elements of a list:

In [ ]:
numbers = [2, 3, -5, 4, -2, 9]
product = 1
for n in numbers:
    product *= n
print(f'The product of the numbers is {product}')

The product of the numbers is 2160


It is also possible to iterate over`numpy` arrays, but we must be a little careful. Consider the following example:

In [13]:
import numpy as np
A = np.random.random((4,4))
for row in A:
    print(row)

[0.24324773 0.83675674 0.81952965 0.67221482]
[0.74814452 0.44339894 0.79562484 0.45387084]
[0.1448084  0.73814563 0.90587627 0.32389809]
[0.2678694  0.92059369 0.01361108 0.60406369]


Notice that this iterates over the *rows* of the two-dimensional array `A`. If we want to iterate over each element separately we can use nested loops:

In [15]:
sum_of_elements = 0
for row in A:
    for value in row:
        sum_of_elements += value
print(f'The sum of the elements of A is {sum_of_elements}')

The sum of the elements of A is 8.93165433236993


### Exercises

1. Compute $2^n$ for the first 100 integers, with $n=0$ being your initial value.

2. Use a `for` loop to compute the first 20 numbers in a  Fibonacci sequence. Fibonacci sequence is defined by the previous numbers
$$x_{n+1}=x_{n}+x_{n-1}$$
where $x_0=0$ and $x_1=1$. 
Fix the following incomplete code to compute the first 20 Fibonacci numbers in a numpy array.
```
F=np.zeros(20)
F[0]=0
F[1]=1
for n in range(FILL, OUT):
  F[?]=
print(F)
```
Note `F[0]` represents $x_0$ and `F[1]` represents $x_1$.

3. Compute the column sum of the matrix A:
```
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, -1, -2, -3],[-4, -5, -6, -7]])
```
Hint: use `col` to iterate.

# `while` loops

`while` loops are similar to `for` loops in that they perform a task repeatedly in a loop. The difference between `while` and `for` loops is that while `for` loops will perform a set task for a predetermined number of iterations, `while` loops will continue performing the loop as a condition is true. Once the condition is false they stop stopped.

```
while <condition>:
    <indented block>
```

Note that while `for` loops had an iteration variable, the `while` loop only relies on the condition being true. However, you can still create a variable that acts like an iteration counter.

Below is an example of a `while` loop that will print out a variable `n` so long as `n` is less than 10. 

In [17]:
n=1
while n<10:
  print(n)
  n+=1
  

1
2
3
4
5
6
7
8
9


However, be careful to make sure you're updating in the loop. The following `while` loop lacks an update for `n`, so it fails to end because the condition is always true.

In [ ]:
n=1
while n<10:
  print(n)
  

#Using `break` and `continue`

We can use `break` to end a `while` loop (this also works for `for` loops).

For `break`, if a condition is satisfied with an `if` statement in a `while` or `for` loop, then we can use break to end the loop. The loop will not proceed with more iterations. Here we take our previous `while` loop and `break` it when the iteration equals 4.

In [33]:
while n<10:
  if(n==4):
    break
  print(n)
  n+=1
  

For `contiue`, if a condition is satisfied with an `if` statement in a `while` or `for` loop, then we can use skip the rest of the actions of the loop BUT we continue the loop. The loop will skip everything after the `continue` and proceed to the next iteration. Here we take our previous `while` loop and `continue` it when the iteration equals 4.

In [38]:
n=0
while n<10:
  n+=1
  if(n==4):
    continue
  print(n)

1
2
3
5
6
7
8
9
10


 Note placement is very important! If we don't update `n` before the `continue` statement then it will be stuck in an infinite loop.

In [ ]:
n=0
while n<10:
  if(n==4):
    continue
  n+=1
  print(n)

#`while` loops and tolerances

We can use other conditions to end our `while` loop as well. For instance if we have a way of calculating error and we'd like it to be below a certain tolerance, then we could 

Let's go through an example that follows along this path. The following expression from Calc 1 can be an approximation to a derivative:

$$f'(x)\approx\tilde{f'}(x)=\frac{f(x+h)-f(x)}{h}$$

where $x$ is the point about which we'd like to evaluate a derivative and $h$ is set distance away from the point. The closer $x+h$ gets to $x$, the more accurate the approximation should be (in theory... there's a more complicated story due to finite precision arithmetic). 

If we use the function $f(x)=e^{x}$ and calculate error to be $e=|f(x)-\tilde{f'}(x)|$, then we can set up a 'while' loop to find how small an $h$ we need to have an error of less than $10^{-3}$. At each iteration the $h$ value is halved.


In [27]:
def dfun(x,h):
  df=(np.exp(x+h)-np.exp(x))/h
  return df

x=2.0
h=4.0
err=1.0 #initial error value
tol=1e-3 # error tolerance
while err>tol:
  h=h/2
  print(h)
  df=dfun(x,h)
  err=abs(np.exp(x)-df)

print('We need h=',h,' to have satisfy a tolerance of less than ',tol)

2.0
1.0
0.5
0.25
0.125
0.0625
0.03125
0.015625
0.0078125
0.00390625
0.001953125
0.0009765625
0.00048828125
0.000244140625
We need h= 0.000244140625  to have satisfy a tolerance of less than  0.001
